import './globals.css'

import type { Metadata } from 'next'
import { JSX } from 'react'

import { Providers } from '@/config/Providers'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

type Props = {
	children: React.ReactNode
}

export default function RootLayout(props: Props): JSX.Element {
	const { children } = props

	return (
		<html lang='en'>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
